### ISSUE TITLE
Get difficulty at arbitrary block height

### ISSUE THREAD

**Issue by dlio** [namecoin/namecoin-legacy#112]
While `namecoind getinfo` and `namecoind getdifficulty` display the **current** difficulty, `namecoind getblock <block_hash>` does not return difficulty info for an arbitrary block in the past.

Is it possible to do this?  There is some code I've written that works across dozens of other coin daemons that breaks with namecoin because of this missing difficulty field.  I've patched together some workarounds for other issues but this one is a significant obstacle to the inclusion of namecoin in various multi-coin projects.

Any help would be much appreciated -- cheers.

**Comment by domob1812** [comment]
Yes, should be possible to do.  I'll give it a try and submit a patch if it is not too much work (which it isn't, presumably).  I think this information is useful, also for all kinds of statistics.

**Comment by phelixbtc** [comment]
Done.

**Comment by dlio** [comment]
Awesome! Thanks a ton -- testing now.

**Comment by dlio** [comment]
Works like a charm; many thanks.
