### ISSUE TITLE
Go language

### ISSUE THREAD

**Issue by tredoe** [namecoin/namecoin-legacy#12]
Could be used Go instead of C++:
- The code would compile in the main systems (linux, os x, windows, freebsd) and architectures (x86, x86-64, arm) without any change
- It has a great library whose API has been frozen for Go 1  
  http://weekly.golang.org/pkg/
- Google is placing trust in Go by adding it to App Engine, Google Code search, and open-sourcing vitess, which it's the core of YouTube's new MySQL serving infrastructure.  
  http://code.google.com/p/vitess/

**Comment by phelixbtc** [comment]
no, sorry
