### ISSUE TITLE
Default Branch

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/namecoin-legacy#126]
Currently "namecoinq-release" is the default branch though the current working branch is "namecoinq"***. This was done so that users who just want to download, build and run by default get the release version. 
But it makes branching and pushing more tedious, because all the time you have to switch from the default "namecoinq-release" to "namecoinq". This a pita by itself but also new developers often fork the wrong branch which means extra work.
Should we switch the default branch to "namecoinq" (the master, current stable working branch) as most projects do?
We could put a notice about the release version in the headline. A possibility to make it more clear would be to remove the version numbers from the working branch and only insert them in the release branch. Opinions?

***Other projects would call this branch "master" and we will probably switch to this common name in the near future.

**Comment by domob1812** [comment]
I think this is a good change.  I also don't think we need to stress it too much, and we should keep the version tags on (the new) master.  Other projects do this as well, and personally I think that everyone who downloads the code from Git should expect to get the "bleeding edge".  They can check out a version tag instead if they want the stable version.  But I'm also fine with a compromise that doesn't involve changing the current system that much all at once.

**Comment by phelixbtc** [comment]
The idea of the release branch was to provide better tested, exactly defined additionally tested official versions to minimize the risk of accidental forks or other serious bugs. 
On the other hand side continuous deployment might help us to earlier notice problems. Are the users ready for this? So far the release versions were quite stable and the trouble for users might not be so bad. 
What about versioning? ("My client crashed, version is 0.3.75ish..."). This is a good argument for releases imho and I want to continue with explicit release Versions for the Windows binaries.

btw, we could set the version suffix for "namecoinq" ("master") to "dev" or so to help distinguish user builds.
