### ISSUE TITLE
CLI parameters parsing error

### ISSUE THREAD

**Issue by i-hate-computers** [namecoin/namecoin-legacy#13]
$ namecoin/src/namecoind -datadir=.namecoin getinfo
{
    "version" : 32466,
    "balance" : 0.00000000,
    "blocks" : 180272,
    "connections" : 8,
    "proxy" : "",
    "generate" : false,
    "genproclimit" : 3,
    "difficulty" : 1733207.51384839,
    "hashespersec" : 0,
    "testnet" : false,
    "keypoololdest" : 1307601253,
    "paytxfee" : 0.00000000,
    "mininput" : 0.00010000,
    "errors" : "URGENT: upgrade required, see http://bitcoin.org/dos for details"
}

but:

$ namecoin/src/namecoind -datadir=.namecoin name_list
error: {"code":-32601,"message":"Method not found"}

**Comment by khalahan** [comment]
=> "blocks" : 180272 : you are querying bitcoin and not namecoin here.
Use parameter "-rpcport=8336" (for example) to start and query namecoin on another port.

(Default port changed to 8336 in this fresh commit : https://github.com/khalahan/namecoin/commit/5bbd4a7b77eacf25b283ddb50b14d097c2fd7df1 :p)

**Comment by i-hate-computers** [comment]
yes, I am stupid idiot :-)
