### ISSUE TITLE
Add RPC support for PowerDNS remote backend

### ISSUE THREAD

**Issue by renne** [namecoin/namecoin-legacy#130]
The nameserver/recursor [PowerDNS](https://www.powerdns.com/) has a backend which can talk JSON over HTTP(S). It's called [Remote Backend](http://doc.powerdns.com/html/remotebackend.html).

By just adding [some additional JSON queries](http://doc.powerdns.com/html/remotebackend.html#remotebackend-api) to the current RPC-API Namecoin can be easily interfaced with an high-performance nameserver/recursor.

**Comment by crosser** [comment]
This (my) project http://www.average.org/pdns-pipe-nmc/ does this.
Trying to include all the lookup logic directly into namecoind would be, in my opinion, unwise.

**Comment by domob1812** [comment]
I've not dived deeply into this matter, but my general opinion is this:  If the requested JSON-RPC commands are of "general use" and relatively low-level / hard to implement without the internal things namecoind knows, then adding is fine.  However, if they are DNS related (only one specific aspect of Namecoin!) and/or relatively specific / high-level, then I agree with @crosser that this is not something we want to have in namecoind directly.

A solution is a separate project, like the one mentioned.  Or, we could include the calls in _NMControl_, which is a high-level interface to the lower-level namecoind.  NMControl already includes some DNS things (also a DNS server and generic routines to resolve .bit domains), so it would fit there potentially.

**Comment by phelixbtc** [comment]
Any news on this? About to close. Sounds like a job for NMControl...
