### ISSUE TITLE
Register with Apple and sign OS X binaries

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-legacy#132]
By default OS 10.9 and above blocks unsigned binaries from opening, so for any of our software to "just work" on OS X we need to sign them regardless of whether they are in the App store or not.

To cover the fees and headache, we could put paid versions of our software up on the store.  I would support revenues (with some sane upper limit) going to whomever maintains the OS X branches .

**Comment by phelixbtc** [comment]
Any news on this? How much would it cost to be able to create signed binaries? For Windows I think it would be rather expensive. Not so sure about selling the client...

**Comment by cassiniNMC** [comment]
$99/year. Always at risk of getting banned, though. There is no Bitcoin or Litecoin App in the AppStore. However, The Blockchain App managed to get in again.

**Comment by indolering** [comment]
I would like to close this myself but the irritating bit is that Apple blocks _all_ non-signed apps by default, so for any of our software to "just work" on OS X  we need to be able sign it.  I'll update the ticket to clarify the need.

**Comment by indolering** [comment]
@JeremyRand could you use FreeSpeechMe funds for this?  You are the build expert, so you would likely need to manage this eventually anyway.

**Comment by JeremyRand** [comment]
Can someone provide a link to background info on this?  I know literally nothing about the code signing and app store schemes used by Apple.  I have no inherent objection to selling binaries to people who wish to support us in that manner; this seems to be common in open-source projects, at least for Android apps.

**Comment by indolering** [comment]
@JeremyRand Ugh, I just looked up the requirements for companies and this might need to be put on ice until we get join the Software Freedom Conservancy.  Try [signing up](https://developer.apple.com/programs/mac/) for the personal one and see if we can use that for now.

**Comment by JeremyRand** [comment]
Looking at the relevant info, I don't think it's worth the money.  Any system that charges developers $99 to develop on the system is doomed to fail (or at least I want it to fail).  If someone wants to setup a BountySource bounty, I have no objection, but I won't be donating.

**Comment by domob1812** [comment]
@JeremyRand I fully agree - IMHO, we shouldn't "waste" any money paying Apple for keeping their users hostage.  Of course, if someone wants to specifically pay for it, they are welcome - as would you be to use the FreeSpeechMe money.  But we should definitely not use any NMDF funds for this.

**Comment by indolering** [comment]
Uhh, so we are willing to cut out a huge swath of our target audience because we don't want to send money to Apple?  We are paying $100/year on SSL certs, why not Apple's certs?

Listen, I get that we hate the current certificate authority scam system, Namecoin is designed to end such security theater.  But if we don't play the game we cannot win.

I'm okay with letting this go for now, we won't have any consumer-level programs for OS X for another 6 months or more, but we will have to pay for these certs at some point.

**Comment by cassiniNMC** [comment]
How do the Bitcoin devs handle it? What happens if you start the Bitcoin.app (downloaded from bitcoin.org) on a fresh Mavericks install? Does it come up with the "Unknown Developer" error? If not, how do they suppress this error?

**Comment by indolering** [comment]
They sign it,

```
➜  ~  codesign -dvvv /Applications/Bitcoin-Qt.app
Executable=/Applications/Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
Identifier=org.bitcoinfoundation.Bitcoin-Qt
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=153121 flags=0x0(none) hashes=7649+3 location=embedded
Hash type=sha1 size=20
CDHash=68b2974f209336f9b90a2435768a0ebac4d3b945
Signature size=8544
Authority=Developer ID Application: BITCOIN FOUNDATION, INC., THE
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Jun 19, 2014, 7:42:50 AM
Info.plist entries=16
TeamIdentifier=not set
Sealed Resources version=1 rules=4 files=11
Internal requirements count=1 size=192
```

Even if Bitcoin **didn't** sign the main app, we will have consumer-specific apps that will need this code signing.

**Comment by JeremyRand** [comment]
Given that this doesn't have anything to do with namecoind/Namecoin-Qt specifically, is it okay to move discussion to the meta repo?

**Comment by phelixbtc** [comment]
ACK. May also be relevant to NMControl.

**Comment by JeremyRand** [comment]
Okay, let's move discussion to https://github.com/namecoin/meta/issues/2 .
