### ISSUE TITLE
ncproxy fails to provide access to tor hidden services via .bit domains.

### ISSUE THREAD

**Issue by crocket** [namecoin/namecoin-legacy#145]
`federalistpaper.bit` is a tor hidden service, and I can't visit it without FreeSpeechMe firefox plugin.

Can ncproxy obviate FreeSpeechMe?

**Comment by JeremyRand** [comment]
Hi,

ncproxy was scrapped in favor of FreeSpeechMe over a year ago.  May I ask why you don't want to use FreeSpeechMe?  Do you just want support for non-Firefox user applications?  There's a pending pull request for FreeSpeechMe which allows this: https://github.com/namecoin/Convergence/pull/5

**Comment by crocket** [comment]
I want to be able to access .onion services via .bit domains in every application, and I generally prefer headless daemons controlled by GUI and CLI clients.

**Comment by crocket** [comment]
If Convergence could be run stable as a standalone, I have no objection to xulrunner.
However, I'm skeptical of xulrunner since it is not desinged to run headless daemons.
I think the issues I submitted to Convergence obviate this issue.
Therefore, I close it.
