### ISSUE TITLE
Merge-mining documentation?

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-legacy#173]
During the aggregation issues, it became apparent that merge-mining namecoin is a PITA.  One pool isn't processing transactions at all and a handful pools with 17% of mining power aren't merge-mining at all.

Why is merge mining such a PITA?  Is it documentation, is it Namecoind?  Would appointing a pool ambassador help?

**Comment by phelixbtc** [comment]
This issue is off topic. Maybe we should rather discuss this on the forum?

**Comment by indolering** [comment]
Sure.

**Comment by sigwo** [comment]
Merge Mining would be better if getblocktemplate was an option via RPC....I have it running but the stats will not update. My stratum sees it (Powerpool), but the front end (simplecoin_multi) that handles stats/payouts doesn't.
