### ISSUE TITLE
support -txindex and -reindex

### ISSUE THREAD

**Issue by testalt** [namecoin/namecoin-legacy#193]
Hi,

I noticed that last version does not support -txindex and -reindex, is there any plan to add support ?

Thanks

**Comment by domob1812** [comment]
`-txindex` is not necessary, as Namecoin keeps an index of all transactions anyway.  (Use `getrawtransaction` or `decoderawtransaction` to access non-wallet transactions.)

This will change when we switch to a version based on the latest Bitcoin Core at some point in the future, but then both arguments will be supported as they are in Bitcoin.  It is not clear when that will be the case, though.

**Comment by testalt** [comment]
Thanks. Namecoind does not return a list of transaction hashes for a block, is there a way to get it ?

**Comment by testalt** [comment]
Specifically, i need to get a list of transaction hashes for a block via RPC

**Comment by domob1812** [comment]
Both `getblock` and `getblockbycount` do that (in the `tx` field).

**Comment by domob1812** [comment]
Closing.
