### ISSUE TITLE
Support batch JSON RPC requests

### ISSUE THREAD

**Issue by erasmospunk** [namecoin/namecoin-legacy#203]
When batching multiple JSON RPC requests the following error is produced:
`{"result":null,"error":{"code":-32700,"message":"Parse error"},"id":null}`
The same technique works with Bitcoin and most of the alt-coins.

**Comment by domob1812** [comment]
You can take a look at https://github.com/domob1812/namecore.  (Still experimental, though!)  I don't think we will be fixing this here, but the report is valid.

**Comment by erasmospunk** [comment]
Glad to hear that it will be fixed in the new codebase. Closing this then.
