### ISSUE TITLE
Fedora 21 Packages Not Available

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/namecoin-legacy#207]
Seems that pmc's packages haven't yet been updated for Fedora 21.  The Fedora 20 packages give the following error on Fedora 21:

namecoin: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory

I see the same issue with another project that's hosted on OpenSUSE's build server... maybe the fix would be on OpenSUSE's end?

**Comment by pmconrad** [comment]
The build environment for Fedora-21 is not (yet) available on OBS. Will enable it for my repo when they have integrated it.

**Comment by JeremyRand** [comment]
Thanks @pmconrad , that's what I figured.  Any idea how long (ballpark) it typically takes OBS to set up their system for a new Fedora release?

**Comment by pmconrad** [comment]
My guess would be a couple of days, but it depends a lot on what else they have on their agenda.

**Comment by JeremyRand** [comment]
OBS has Fedora 21 now.

**Comment by pmconrad** [comment]
Yes, I noticed. The build servers are currently overloaded, it will take a while until the namecoin packages have been built.

**Comment by pmconrad** [comment]
Builds finished.

**Comment by JeremyRand** [comment]
I'm only seeing i686 builds; are there supposed to be x64 builds as well?

**Comment by pmconrad** [comment]
x86_64 repository state is being recalculated, should appear soon. The build as such is complete.

**Comment by JeremyRand** [comment]
Confirmed working, closing.  Thanks.

**Comment by foxcool** [comment]
bash-4.3 $ sudo yum install namecoin
Loaded modules: langpacks
Dependency resolution
-> Check Script
---> Package namecoin.x86_64 0: 0.3.80-3.1 marked for installation
-> Processing Dependency: libboost_filesystem.so.1.53.0 () (64bit) Package: namecoin-0.3.80-3.1.x86_64
-> Processing Dependency: libboost_system-mt.so.1.53.0 () (64bit) Package: namecoin-0.3.80-3.1.x86_64
-> Processing Dependency: libboost_system.so.1.53.0 () (64bit) Package: namecoin-0.3.80-3.1.x86_64
-> Processing Dependency: libboost_program_options.so.1.53.0 () (64bit) Package: namecoin-0.3.80-3.1.x86_64
-> Processing Dependency: libboost_thread-mt.so.1.53.0 () (64bit) Package: namecoin-0.3.80-3.1.x86_64
-> Checking dependencies over
Error: Package: namecoin-0.3.80-3.1.x86_64 (home_p_conrad_coins)
            You must: libboost_system.so.1.53.0 () (64bit)
Error: Package: namecoin-0.3.80-3.1.x86_64 (home_p_conrad_coins)
            You must: libboost_thread-mt.so.1.53.0 () (64bit)
Error: Package: namecoin-0.3.80-3.1.x86_64 (home_p_conrad_coins)
            You must: libboost_system-mt.so.1.53.0 () (64bit)
Error: Package: namecoin-0.3.80-3.1.x86_64 (home_p_conrad_coins)
            You must: libboost_filesystem.so.1.53.0 () (64bit)
Error: Package: namecoin-0.3.80-3.1.x86_64 (home_p_conrad_coins)
            You must: libboost_program_options.so.1.53.0 () (64bit)

---

bash-4.3 $ sudo yum install boost-system
Loaded modules: langpacks
Package boost-system-1.55.0-8.fc21.x86_64 already installed, and this latest version.
perform nothing
bash-4.3 $ sudo yum install boost-thread
Loaded modules: langpacks
Package boost-thread-1.55.0-8.fc21.x86_64 already installed, and this latest version.
perform nothing

installed packages fresher than required

**Comment by pmconrad** [comment]
Are you sure you're using the Fedora_21 repo? In Fedora_21, namecoin is linked against boost 1.55.

**Comment by foxcool** [comment]
bash-4.3$ cat /etc/yum.repos.d/home:p_conrad:coins.repo 
[home_p_conrad_coins]
name=Lots of Cryptocoin clients + miners (Fedora_21)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/home:/p_conrad:/coins/Fedora_21/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/home:/p_conrad:/coins/Fedora_21/repodata/repomd.xml.key
enabled=1

Is this config good?

**Comment by pmconrad** [comment]
That looks like it should.

Is it possible that you have another repository configured that contains a namecoin package?
Or have you upgraded your system from an older fedora version and you have an old namecoin package cached somewhere?

This is the version you should be installing: https://build.opensuse.org/package/binary/home:p_conrad:coins/namecoin?arch=x86_64&filename=namecoin-0.3.80-3.1.x86_64.rpm&repository=Fedora_21
If all else fails, please download the RPM from the above URL and try to install it manually.
