### ISSUE TITLE
When I try to build, I get an error because of rescanfornames()

### ISSUE THREAD

**Issue by rafaeldotjs** [namecoin/namecoin-legacy#22]
I'm trying to build namecoind. I get this error "...init.cpp:555: undefined reference to rescanfornames();" and the compilation fails.

I built from an old version in Vinced's branch, and it worked fine.

**Comment by JeremyRand** [comment]
Hi @rjquery , can you try again with the namecoin-qt branch?  Also, exactly what terminal commands are you using to build?

**Comment by crosser** [comment]
I got the same problem after fresh pull these days. For some reason, obj/nogui/namecoin.o was not built, and was not included in the linking step by make. After compiling and linking by hand, I can no longer reproduce it. "make clean", then "make" and it's built successfully. Miracle. Using makefile.unix.
