### ISSUE TITLE
repo key expired

### ISSUE THREAD

**Issue by yu210148** [namecoin/namecoin-legacy#224]
Hi All,

the GPG key for deb http://download.opensuse.org/repositories/home:/p_conrad:/coins/xUbuntu_14.04/ / appears to have expired.  

I know this is an issue for the package maintainer rather than the upstream developers but I'm not sure how to get in touch with the maintainer and thought someone here might know.

The output of apt-get update on kubuntu 14.04 shows:

``` bash
Reading package lists... Done
W: GPG error: http://download.opensuse.org  Release: The following signatures were invalid: KEYEXPIRED 1427360970
```

The expected output is the same without the message about the expired key.

I believe the expired key in question is found here:

```
http://download.opensuse.org/repositories/home:/p_conrad:/coins/xUbuntu_14.04/
```

If anyone knows who's maintaining this package could they please pass this on to them?

Thanks in advance.

**Comment by JeremyRand** [comment]
@pmconrad Can you look at this?

**Comment by pmconrad** [comment]
Hm... the key was automatically extended yesterday, but the repo wasn't updated. I have triggered a rebuild, hope that'll help.

**Comment by yu210148** [comment]
Humm.... Not sure if that worked.  Does it usually take this long to propagate?

**Comment by pmconrad** [comment]
Have you downloaded and re-added the key?

```
wget http://download.opensuse.org/repositories/home:p_conrad:coins/xUbuntu_14.04/Release.key
sudo apt-key add - < Release.key  
```

**Comment by yu210148** [comment]
Ah, yep, that'd do it. :)
