### ISSUE TITLE
namecoind not working, unclear why

### ISSUE THREAD

**Issue by bloff** [namecoin/namecoin-legacy#233]
When I run it I get:

```
************************
EXCEPTION: 22DbRunRecoveryException       
DbEnv::open: DB_RUNRECOVERY: Fatal error, run database recovery       
bitcoin in AppInit()       

terminate called after throwing an instance of 'DbRunRecoveryException'
  what():  DbEnv::open: DB_RUNRECOVERY: Fatal error, run database recovery
Aborted
```

I also have the problem that namecoin-qt crashes on exit ([link to git issue](https://github.com/namecoin/namecoin/issues/143)).

**Comment by phelix** [comment]
What system are you on? I assume you are using 0.3.80. You could try renaming your datadir to something else and see if it works from a clean table (you will have to redownload the blockchain).

**Comment by JeremyRand** [comment]
Closing since there isn't enough information to diagnose anything and OP hasn't responded to a request for more info.
