### ISSUE TITLE
listtransactions command from not working correct

### ISSUE THREAD

**Issue by asihud** [namecoin/namecoin-legacy#235]
listtransactions "account" count from
if the from parameter is more than the amount of transactions user has in account,
the transactions will not return zero transactions list (as it should) , it will make the transaction zero.
this is not how bitcoind or litecoind client works.

**Comment by JeremyRand** [comment]
Hi,

Can you try with Namecoin Core?
https://github.com/namecoin/namecoin-core .  (namecoin-legacy repo is no
longer actively maintained.)

Thanks!

**Comment by asihud** [comment]
the core work fine.
the namecoin website linux binary should be updated to the namecoin-core version instead of the legacy.
