### ISSUE TITLE
Please add Ubuntu 16.04 builds to downloads

### ISSUE THREAD

**Issue by josephbisch** [namecoin/namecoin-legacy#236]
@pmconrad

Could you add builds for Ubuntu 16.04? Someone mentioned on irc that there aren't any.

Thanks!

**Comment by pmconrad** [comment]
Added, built successfully. Thanks for pinging.

**Comment by josephbisch** [comment]
Thanks, but were the Ubuntu 15.10 instructions supposed to disappear from the download page? It's not a big deal, because 15.10 end of life is this July anyway. So people should be moving to 16.04, or 16.10 anyway, if they want to use a supported version of Ubuntu.

Also, looking at the binary packages for 16.04, it appears to only have i386 available, whereas 14.04 has amd64, arm64, armhf, and ppc64el in addition to i386.

**Comment by pmconrad** [comment]
I  thought someone who hasn't installed namecoin on Ubuntu-15.10 by now is unlikely to do that until July.

The i386-only is intentional, due to an inconsistency somewhere (I believe it was in openssl). IIRC there's a forum thread about it. The *64-builds shouldn't exist at all due to missing dependencies. Don't know why they're showing up, I'll try to disable them explicitly.

**Comment by josephbisch** [comment]
Thanks, I'm closing this issue now.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 05/21/2016 02:57 PM, Peter Conrad wrote:

> I thought someone who hasn't installed namecoin on Ubuntu-15.10 by
> now is unlikely to do that until July.
> 
> The i386-only is intentional, due to an inconsistency somewhere (I 
> believe it was in openssl). IIRC there's a forum thread about it.
> The *64-builds shouldn't exist at all due to missing dependencies.
> Don't know why they're showing up, I'll try to disable them
> explicitly.

If you're referring to the issue disclosed by sipa last year, any
transactions that could trigger the OpenSSL consensus bug are now
rejected by miners thanks to the BIP66 softfork.  So, as far as I
know, 64-bit 0.3.80 binaries are just as safe as 32-bit 0.3.80
binaries.  (They both trust the miners somewhat.)

Is there some other issue that I'm unaware of?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJXQQTgAAoJEAHN/EbZ1y06NRsP+gOJ0uWFzhdBrbBHqEcsH+id
4LbYlb2BSyAkGAEVv2+nuS7eCL3J5I7h2QD18h7RQ7/ODVeFbZiDefO9diLYQ806
ivaW7iSjBdQYLUmhSEdHRQRB6F/cHFNaHRXN3GYIaSBM4oaTrKN7ZrYvxJbk1g2w
BMlfXaSejGvB6OfQe21+E5yTJzb/fM+UKd3V+qeFKXZakNM36m1K1l7zyjvkLagB
RcV8s0+gE8iXGk66h8dTmHaxMpIHKnxBpT2qqL2yGdPSaqFYML0sL/d2s0GAIs0H
t1nWprxUHY5g5POaWr7FSMN4J1THzTMyYsRuqlVzoWmTIYK03Tx3FS/USjFKn4ic
0acK20oOG5h1eR07mfChP4j+F+aviS4KTNaebnEvmi23OEQ9iY/6d6fO2f4UAx67
vgxO90wGwwfDRMOy1fO95O9AwTdGNjG1Uu71A9P/Vu5rK3gYLaJ/zfJWwbd1vfFY
n5ptnP+5lPdGR2EEEiqLa+XXtd7gzmm+oF5A4GP2m+H5v2qAaEv8jFVe6HdRq6rD
y9n6tBFlWnOmHZgPSdvsPjU4M4JvIqrK8LvTEhYtqcvCmuQ5TAHWygSXtEjSuazb
5A4Mgzv2AUykg8tS+vsCQZGYuTzaGv9SCusrbwS5q4shATiLdDVR4mbcDetnKX9K
WrYIVdmJ0IW5sda6Jh60
=aclA
-----END PGP SIGNATURE-----

**Comment by pmconrad** [comment]
> So, as far as I know, 64-bit 0.3.80 binaries are just as safe as 32-bit 0.3.80 binaries.

Thanks, AFAIR that was the issue. Re-enabled 64bit builds.
