### ISSUE TITLE
forum.namecoin.org registration is useless

### ISSUE THREAD

**Issue by sanyanet2** [namecoin/namecoin-legacy#238]
After registration forum does not grant user any rights. No post creation, no thread creation, nothing.
Email is verified.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

sanyanet2:
> After registration forum does not grant user any rights. No post
> creation, no thread creation, nothing. Email is verified.

This is not a bug in Namecoin-Legacy; website issues should go in the
namecoin.org repo.

There should be a notice at the top of the forum when you log in as a
new user, saying "Information: Add yourself to the 'Self confirmed
users' group to be able to post messages".  If you click the link in
that notice, you will be able to add yourself to that group, which
will grant you posting privileges.

(I just tested this with a fresh user account, and it works fine on my
end.)

If that notice is not visible for you, please open a bug in the
namecoin.org repo with information that might help reproduce the issue.

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYYZ9NAAoJELPy0WV4bWVwwsQP/j+zk1R8ok0sNmF5hfI/UPvd
1BnUDncu00oVXEluwpqCzf2rKc+65gTQ9VugflHUFBqahrIALY+n1JNb2lSd/DBx
XBlhRFG+DzpoZ9PHFyTELhO64OBIvT15b9cD52yIN8D4ipAp30mNFQ6Ppx2mUEr5
3I7qD7nq82ovsr4TMtuRjT2TMZazSzjziy4FqiKhQxOMY+w3VebSV9w85QbC6Eh5
xG2mr5J6/UgCGix8MSrKmE0j/lIF9MZn9Vdk/g5yjwKOFa1HRjTvoIZo5K8P41Bs
stbMw6VZiXuSMO2mlzZtDoHVmIpsLdX7t5wLVoV7HAYGvjeb2dfS3XFn3ToHV19f
/X/QdhfPEU1gjsEPOs6b/Amfcd5VBKoN2HqL6slfxvNy47F6WFPPrT4fqwAs/xC3
kOvLrIoVIphpJiz6AV+aJYqZt0AZZhFIg3NeWkKhFebUYesdpgduJEVN1j/TTnb5
UYts6ZDPcSwRHKx8WnWyhCpO7Q8L7nboz0EiNQkpLwyeSVq2Nwo/UKIz/4jMNreT
Oz4rg+t3w6PlVN9fWXER07UbcDWbUBjumlTHYnKmtvP2Bhb5jEFgO/BJzhuw1AE8
C9v09fCy5qp2G1szMgnr4y5zqO4392QsQrP+OwdqUu1VpC3yghX2fokN1Tr4G5dX
NlJ2/SxCwAZ66F0l2c/I
=if1p
-----END PGP SIGNATURE-----
