### ISSUE TITLE
Key Expired: 2017-06-04 for p_conrad repository

### ISSUE THREAD

**Issue by Raptus1** [namecoin/namecoin-legacy#239]
Any change this will be updated soon?

**Comment by pmconrad** [comment]
I have updated the key. You may have to download
the key with the new signature, I don't know if it will update
automatically.

-- 
Cyrano UG (haftungsbeschränkt)
Alicestr. 102
63263 Neu-Isenburg
Germany

Tel.: +49 6102 821206

Geschäftsführer: Peter Conrad

AG Offenbach
HRB Nr. 47931

USt-ID: DE296491819

**Comment by Raptus1** [comment]
Thank you, I did the manual key-update.

BTW: is there a specific reason for using SHA1?

**Comment by pmconrad** [comment]
Keys and signatures are generated by the open build service. I have no control over them. (Except that I can request that the signature be updated.)

**Comment by Raptus1** [comment]
Got it, thanks again.
