### ISSUE TITLE
can't build namecoind , warning about namecoin.conf

### ISSUE THREAD

**Issue by Gigabear** [namecoin/namecoin-legacy#25]
Warning: To use namecoind, you must set rpcpassword=<password>
in the configuration file: /root/.namecoin/namecoin.conf
If the file does not exist, create it with owner-readable-only file permissions.

have tried many times to set permissions and password and I did not succeed to install it. Using Backtrack5r3. Thank you in advance.

**Comment by phelixbtc** [comment]
Sounds like a problem starting not installing. Closing because so old.

**Comment by JeremyRand** [comment]
Looks like @Gigabear was running namecoind as root?
