### ISSUE TITLE
Create Debian packaging repository

### ISSUE THREAD

**Issue by pataquets** [namecoin/namecoin-legacy#27]
There is a namecoin LaunchPad team at https://launchpad.net/~namecoin, but no NC project.
As per Debian policies, packaging directory files should be not in the main source tree.
However, if a namecoin-debian repository was available, I would be able to create a LP project page and configure the LP buildbot to automatically import NC sources and set up a daily builds repo using LaunchPad's PPA features.

**Comment by phelixbtc** [comment]
AFAIK there is a debian package by now.

**Comment by pataquets** [comment]
Still no LP project page nor automated import/builds available. Applied at LP to help move it forward.
