### ISSUE TITLE
Japanese Translation

### ISSUE THREAD

**Issue by jonwaller** [namecoin/namecoin-legacy#28]
I'd like to translate Namecoin into Japanese. What steps do I need to take? Thanks.

**Comment by Pagel1928** [comment]
The namecoind strings are hardcoded in, so its difficult to translate. However the GUI interface (namecoinq project) can easily be translated.

You can take the Japanese translation of bitcoin-qt as a base:
https://github.com/bitcoin/bitcoin/blob/master/src/qt/locale/bitcoin_ja.ts

And add any additional Japanese translations necessary to the namecoin locale:
https://github.com/namecoinq/namecoinq/blob/master/src/qt/locale/bitcoin_ja.ts

I'm unsure if there is anything else you need to change, there may be some hardcoded strings.

**Comment by indolering** [comment]
@jonwaller setting up an online translation system would be a big help.  Right now we use QT translation tools but contributing requires a lot more dedication.  With something like [Trasnifex](https://www.transifex.com/) it would be much easier to port everything over as we could throw up most of the Bitcoin translation and then have random volunteers do touch-up work without having to isntall a software suite.

**Comment by jonwaller** [comment]
Indeed. Editing resource files is a bit confusing for non-techie translators.

I'll see what I can do with the ts file above though. Thanks.
