### ISSUE TITLE
namecoind unresponsive and slow to pick up

### ISSUE THREAD

**Issue by crosser** [namecoin/namecoin-legacy#33]
I am trying to run this version:

```
    commit c4e0e82ffc1b24f0bd5450f47bd6055256ae75e7
    Merge: 7bdfe14 89a09d7
    Author: khalahan <khal@dot-bit.org>
    Date:   Thu Oct 31 13:58:26 2013 +0100
```

on ubuntu saucy 64bit.

It starts to pick up on the chain, but after about 45000 blocks becomes very slow to pick up, like one block per minute. At the same time it becames very slow to respond to `getinfo` - about 20 seconds or more. There are no signs of excessive use CPU or other resources. I noticed other things that look weird:
- negative `lastseen` and `lasttry` in the debug log:

```
IRC got join
AddAddress(100.2.103.115:8334)
IRC got new address: 100.2.103.115:8334
connection timeout
trying connection 120.147.81.79:8334 lastseen=-0.9hrs lasttry=-385568.2hrs
connected 120.147.81.79:8334
sending: version (85 bytes) 
trying connection 24.126.240.124:8334 lastseen=-0.9hrs lasttry=-385568.2hrs
connect() failed after select(): Connection refused
trying connection 174.57.19.253:8334 lastseen=-0.9hrs lasttry=-385568.2hrs
accepted connection 207.118.70.253:57035
connected 174.57.19.253:8334
```
- most interesting, according to `strace`, there is a ready socket that is not read/written after `select()`:

```
[pid 10724] nanosleep({0, 9998571}, NULL) = 0
[pid 10724] select(32, [6 20 23 25 26 27 28 29 31], [], [20 23 25 26 27 28 29 31], {0, 50000}) = 1 (in [28], left {0, 49996})
[pid 10724] nanosleep({0, 9998657}, NULL) = 0
[pid 10724] select(32, [6 20 23 25 26 27 28 29 31], [], [20 23 25 26 27 28 29 31], {0, 50000}) = 1 (in [28], left {0, 49996})
[pid 10724] nanosleep({0, 9998907}, NULL) = 0
```

You can see that `select()` returns one ready file descriptor, but there is no subsequent `read` or `write` operation. I thought that the program might be losing track of the file descriptor, which could potentially cause the trouble that I observe.

**Comment by phelixbtc** [comment]
Closing because there were some changes. Please retry with the latest version and reopen if the problem persists.

**Comment by JeremyRand** [comment]
I encountered a similar issue once, I was able to fix it by renaming wallet.dat until the blockchain download was complete.  Maybe it was a partially corrupt wallet?
