### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by sudosurootdev** [namecoin/namecoin-legacy#36]
While building namecoind from source, on Ubuntu 13.04, I'm getting an error: 

```
ld: cannot find -lgthread-2.0
```

I believe that it is only needed for namecoin-qt. So, if libgtk2.0-dev is only needed for QT than it should not fail when running 

```
make -f makefile.unix namecoind 
```

**Comment by phelixbtc** [comment]
Can anybody confirm this?

**Comment by domob1812** [comment]
I don't know for sure (since I've installed the library anyway), but possibly gthread is used for threading also in the daemon - may it be a dependency of Boost's thread library?  (Just a wild guess, though.)
