### ISSUE TITLE
Post-install/first-run script

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-legacy#40]
Jeremy_Rand and Indolering created the following post-install script to configure namecoin.conf:

```
mkdir -p ~/.namecoin && \
echo "rpcuser=`whoami` \n\
rpcpassword=`openssl rand -hex 30` \n\
rpcport=8334" > ~/.namecoin/namecoin.conf
```

This should included in the standard installer as part of the first-run setup, it would be much more secure and it all needs to be done anyway.

The `openssl rand -hex 30` should probably be replaced with a better, 20-digit random number that has a larger character pool.

**Comment by indolering** [comment]
As the initial blockchain setup takes a long time, it would be feasible to provide a post-install script which downloads a GPG-signed blockchain.

The logistics have already been worked out, Ryan-C and Indolering would post an updated blockchain nightly/weekly on Archive.org.  The URL can remain fixed and because Archive.org supports [mutable torrents](http://www.bittorrent.org/beps/bep_0039.html) we can use an embeddable Torrent client or simply require Aria2 in the install phase. This way we get a torrent distro, free bandwidth form the Archive.org project, and it is very easy to add additional peers.

However, there should be an option to download from a local S3 mirror as VM's within S3 have very fast access to this mirror and the bandwidth is free.

This, of course, becomes less of a concern with UXTO and boostrap.dat files (the latter of which is constrained by processing time, not bandwidth) but we are far from that goal.

**Comment by indolering** [comment]
Make sure that the script only uses alphanumeric passwords, non-alphanumeric passwords will likely mess with RPC clients.

**Comment by phelixbtc** [comment]
All great ideas but we don't even have an installer yet :)

**Comment by indolering** [comment]
We should actually close this as Domob and everyone basically agreed that we should get rid of auth requirements for read-only data operations.  A GUI should package this up as part of the installer, but they will figure that out on their own.
