### ISSUE TITLE
Compile statically linked fails => dynamically?

### ISSUE THREAD

**Issue by kernoelpanic** [namecoin/namecoin-legacy#41]
Hi,

when compiling `make -f makefile.unix` on sabayon linux the following entry in the make files causes some confusion of the linker (since the required libs are not available as static libs) and in the end `ld` is not able to finde the libs that are specified useing `-l *`:

```
[...] -Wl,-Bstatic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -Wl,-Bdynamic -l gthread-2.0 -l z -l dl -l pthread
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_system
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_filesystem
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_program_options
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lboost_thread
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lssl
/usr/lib/gcc/x86_64-pc-linux-gnu/4.7.3/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
make: *** [namecoind] Error 1
```

The removal of the `-Wl,-Bstatic` option, so that everything compiles dynamically linked, resolves the problem: 

```
diff --git a/src/makefile.unix b/src/makefile.unix
index ecaaef4..573ed12 100644
--- a/src/makefile.unix
+++ b/src/makefile.unix
@@ -12,7 +12,6 @@ DEFS=-DNOPCH -DFOURWAYSSE2 -DUSE_SSL

 # for boost 1.37, add -mt to the boost libraries
 LIBS= \
- -Wl,-Bstatic \
    -l boost_system \
    -l boost_filesystem \
    -l boost_program_options \
@@ -34,7 +33,6 @@ bitcoind: USE_UPNP:=0
        endif

 LIBS+= \
- -Wl,-Bdynamic \
    -l gthread-2.0 \
    -l z \
    -l dl \
```

Is there any particular reason why you wanted to compile it with -static?

Some system info:

```
$ ld --version
GNU ld (GNU Binutils) 2.23.1
$ gcc --version
gcc (Gentoo Hardened 4.7.3 p1.0, pie-0.5.5) 4.7.3
$ uname -s -r -m 
Linux 3.12.0-sabayon x86_64
```

**Comment by itoffshore** [comment]
I had the same problem building a package for Alpine Linux - fixed with:

```
 --- src/Makefile
 +++ src/Makefile.new
 @@ -21,13 +21,13 @@
 LIBBOOST_SUFFIX=

 LIBS= \
 - -Wl,-Bstatic \
 + -Wl,-Bdynamic \
 -l boost_system$(LIBBOOST_SUFFIX) \
 -l boost_filesystem$(LIBBOOST_SUFFIX) \
 -l boost_program_options$(LIBBOOST_SUFFIX) \
 -   -l boost_thread$(LIBBOOST_SUFFIX) \
 +   -l boost_thread-mt$(LIBBOOST_SUFFIX) \
 -l boost_chrono$(LIBBOOST_SUFFIX) \
 -   -l db_cxx \
 +   -l db_cxx$(BDB_LIB_SUFFIX) \
 -l ssl \
 -l crypto
```

To be able to build with the latest miniupnpc libraries:

```
 --- src/net.cpp
 +++ src/net.cpp.new
 @@ -1087,7 +1087,7 @@

 #ifndef __WXMSW__
     r = UPNP_AddPortMapping(urls.controlURL, data.first.servicetype,
 -                          port, port, lanaddr, 0, "TCP", 0);
 +                          port, port, lanaddr, 0, "TCP", 0, "0");
 #else
     r = UPNP_AddPortMapping(urls.controlURL, data.first.servicetype,
                        port, port, lanaddr, 0, "TCP", 0, "0");


 $ ld --version
 GNU ld (GNU Binutils) 2.23.2
 $ gcc --version
 gcc (Alpine 4.8.2) 4.8.2

 Alpine Linux 2.7.5 (uclibc) 32bit
```

**Comment by itoffshore** [comment]
This issue can be fixed with the following patch:

```
--- src/Makefile
+++ src/Makefile.new
@@ -9,14 +9,10 @@
 DEFS += -DBOOST_THREAD_USE_LIB

 INCLUDEPATHS= \
-       -I../libs/openssl-1.0.1e/include \
-       -I../libs/db-4.7.25.NC/build_unix \
-       -I../libs/boost_1_50_0
+       -I/usr/include

 LIBPATHS= \
-       -L../libs/openssl-1.0.1e \
-       -L../libs/db-4.7.25.NC/build_unix \
-       -L../libs/boost_1_50_0/stage/lib
+       -L/usr/lib

 LIBBOOST_SUFFIX=

@@ -25,11 +21,12 @@
    -l boost_system$(LIBBOOST_SUFFIX) \
    -l boost_filesystem$(LIBBOOST_SUFFIX) \
    -l boost_program_options$(LIBBOOST_SUFFIX) \
-   -l boost_thread$(LIBBOOST_SUFFIX) \
+   -l boost_thread-mt$(LIBBOOST_SUFFIX) \
    -l boost_chrono$(LIBBOOST_SUFFIX) \
-   -l db_cxx \
    -l ssl \
-   -l crypto
+   -l crypto \
+ -Wl,-Bdynamic \
+   -l db_cxx$(BDB_LIB_SUFFIX) 

 namecoin: USE_UPNP:=1
    ifdef USE_UPNP
```

Perhaps start a separate Makefile for Unix ?

**Comment by phelixbtc** [comment]
Windows uses a separate one, makefile.mingw.
The -mt suffix does not seem to do anything: edit: corrected link: http://stackoverflow.com/questions/3031768/boost-thread-linking-boost-thread-vs-boost-thread-mt

**Comment by itoffshore** [comment]
The -mt suffix is to build using multi threaded versions of the boost libraries - bitcoin uses the following multithreaded libraries (taken from the current 0.91 Makefile):

```
BOOST_LIBS = -L/usr/lib -lboost_system -lboost_filesystem -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt 
```

Using the above multithreaded libraries in Namecoin also compiles successfully - in the following patch I have also set the unpnp libraries to build statically: 

```
--- src/Makefile
+++ src/Makefile.new
@@ -9,14 +9,10 @@
 DEFS += -DBOOST_THREAD_USE_LIB

 INCLUDEPATHS= \
-       -I../libs/openssl-1.0.1e/include \
-       -I../libs/db-4.7.25.NC/build_unix \
-       -I../libs/boost_1_50_0
+       -I/usr/include

 LIBPATHS= \
-       -L../libs/openssl-1.0.1e \
-       -L../libs/db-4.7.25.NC/build_unix \
-       -L../libs/boost_1_50_0/stage/lib
+       -L/usr/lib

 LIBBOOST_SUFFIX=

@@ -24,16 +20,17 @@
  -Wl,-Bstatic \
    -l boost_system$(LIBBOOST_SUFFIX) \
    -l boost_filesystem$(LIBBOOST_SUFFIX) \
-   -l boost_program_options$(LIBBOOST_SUFFIX) \
-   -l boost_thread$(LIBBOOST_SUFFIX) \
-   -l boost_chrono$(LIBBOOST_SUFFIX) \
-   -l db_cxx \
+   -l boost_program_options-mt$(LIBBOOST_SUFFIX) \
+   -l boost_thread-mt$(LIBBOOST_SUFFIX) \
+   -l boost_chrono-mt$(LIBBOOST_SUFFIX) \
    -l ssl \
-   -l crypto
+   -l crypto \
+ -Wl,-Bdynamic \
+   -l db_cxx$(BDB_LIB_SUFFIX)  

 namecoin: USE_UPNP:=1
    ifdef USE_UPNP
-       LIBS += -l miniupnpc
+       LIBS += -Wl,-Bstatic -l miniupnpc
        DEFS += -DUSE_UPNP=$(USE_UPNP)
    endif
    ifneq "$(MINGW)" ""
@@ -53,7 +50,7 @@

 namecoind: USE_UPNP:=0
    ifdef USE_UPNP
-       LIBS += -l miniupnpc
+       LIBS += -Wl,-Bstatic -l miniupnpc
        DEFS += -DUSE_UPNP=$(USE_UPNP)
    endif
    ifneq "$(MINGW)" ""
```

I think it will be useful to speak to the Bitcoin developers to ask how they setup their sources & macros to use autoconf / automake for the 0.91 release. This would eliminate a lot of linking errors & would allow namecoin to be built as a completely static application.

**Comment by itoffshore** [comment]
Bitcoin links dynamically to the various libraries so there is not much point building statically if you are going to run both bitcoin & namecoin. The final patch should probably be:

```
--- src/Makefile
+++ src/Makefile.new
@@ -9,27 +9,23 @@
 DEFS += -DBOOST_THREAD_USE_LIB

 INCLUDEPATHS= \
-       -I../libs/openssl-1.0.1e/include \
-       -I../libs/db-4.7.25.NC/build_unix \
-       -I../libs/boost_1_50_0
+       -I/usr/include

 LIBPATHS= \
-       -L../libs/openssl-1.0.1e \
-       -L../libs/db-4.7.25.NC/build_unix \
-       -L../libs/boost_1_50_0/stage/lib
+       -L/usr/lib

 LIBBOOST_SUFFIX=

 LIBS= \
- -Wl,-Bstatic \
+ -Wl,-Bdynamic \
    -l boost_system$(LIBBOOST_SUFFIX) \
    -l boost_filesystem$(LIBBOOST_SUFFIX) \
-   -l boost_program_options$(LIBBOOST_SUFFIX) \
-   -l boost_thread$(LIBBOOST_SUFFIX) \
-   -l boost_chrono$(LIBBOOST_SUFFIX) \
+   -l boost_program_options-mt$(LIBBOOST_SUFFIX) \
+   -l boost_thread-mt$(LIBBOOST_SUFFIX) \
+   -l boost_chrono-mt$(LIBBOOST_SUFFIX) \
    -l db_cxx \
    -l ssl \
-   -l crypto
+   -l crypto  

 namecoin: USE_UPNP:=1
    ifdef USE_UPNP
```

**Comment by itoffshore** [comment]
You will also need to change the Makefile generated by qmake in the top level of the source:

```
sed -i 's/-lboost_thread/-lboost_thread-mt/g' ./Makefile
sed -i 's/-lboost_program_options/-lboost_program_options-mt/g' ./Makefile
sed -i 's/-lboost_chrono/-lboost_chrono-mt/g' ./Makefile
```

**Comment by phelixbtc** [comment]
Sorry, I posted the wrong link above. I was trying to say that the particular change from "boost_thread" to "boost_thread_mt" you proposed above without changing the others does not make any difference: http://stackoverflow.com/questions/3031768/boost-thread-linking-boost-thread-vs-boost-thread-mt

On windows all boost libraries are compiled with multi threading support exclusively. This is reflected in the makefile via the boost suffix environment variable (easywinbuilder: @set BOOSTSUFFIX=-mgw46-mt-1_54). At least on windows I would suggest we keep things like that because the version number comes before "-mt-".

Is there any advantage/disadvantage to compiling statically or dynamically other than the obvious single or separate files?

**Comment by itoffshore** [comment]
On Alpine Linux (& I think also on Gentoo) /usr/lib/libboost*.la shows the multithreaded & normal boost libraries as separate files (& not as symlinks to each other) - for boost_thread there is only the multithreaded version of the library (libboost_thread-mt.a).

Building with dynamic linking is the standard way on Linux due to the use of Package Managers (but makes sense on Windows to avoid 'dll hell'):

https://stackoverflow.com/questions/21876174/linux-c-c-standard-library-static-vs-dynamic-linking

If Bitcoin builds dynamically it does not make much sense to build Namecoin for Linux statically (if you are using both applications on the same system).

**Comment by JeremyRand** [comment]
Hi,

My understanding is that Bitcoin tries to link statically in many cases because a small change in a library (even a bug fix) could affect blockchain validation, which might cause a consensus failure.  For this reason Bitcoin strongly discourages independent distribution of packages.

**Comment by itoffshore** [comment]
A bit more info here on building statically: https://github.com/bitcoin/bitcoin/issues/3781 & https://github.com/bitcoin/bitcoin/pull/4042 (bitcoin currently builds dynamically).

The arguments for building statically seem to be:

Libboost - build statically if the libraries are not available on your distribution 
OpenSSL - build statically if you are using Red Hat 6.5 (which doesn't have ECDSA support)

NOT recommended to build statically = libc(++) / qt

One argument against building OpenSSL statically is future vulnerabilities (such as http://heartbleed.com)

Alpine Linux has libraries for libboost & OpenSSL with ECDSA so for me it makes sense to build dynamically with the last patch above.

**Comment by phelixbtc** [comment]
Spring cleanup: do we want to make any changes for this issue?

**Comment by itoffshore** [comment]
Static compiling really only makes sense on Windows to avoid "dll hell".
I don't think it's a good idea on Linux in case any more bugs on OpenSSL
exist.

There is no harm in adding "-mt" to the libboost libraries - they may be
symlinks on Ubuntu - but are not on Gentoo / Alpine.

**Comment by JeremyRand** [comment]
Here is the relevant post by a bunch of the Bitcoin developers discouraging dynamic linking:

http://bitcoinmagazine.com/5858/linux-distribution-packaging-and-bitcoin/

**Comment by phelixbtc** [comment]
Closing as outdated. Please submit specific pull requests to continue the discussion.
