### ISSUE TITLE
namecoind importprivkey <private key> <label> - does not return

### ISSUE THREAD

**Issue by wozz** [namecoin/namecoin-legacy#56]
when I run this command, it doesn't return (or doesn't within a reasonable time):

> namecoind importprivkey <private key> <label>

I have to end up killing namecoind and rerunning it.  Once it starts again, the key seems to have been imported properly.

**Comment by muneeb-ali** [comment]
this is because by default, namecoin does a rescan of the blockchain on importprivkey

```
importprivkey <namecoinprivkey> [label] [rescan=true]
```

you have to pass "false" for rescan of the blockchain and then the command will return within a second

**Comment by wozz** [comment]
Thanks!
