### ISSUE TITLE
Namecoin daemon installation

### ISSUE THREAD

**Issue by Shirlpris** [namecoin/namecoin-legacy#64]
Currently am trying to implement namecoin daemon, followed standard daemon installation steps. For "make -f makefile.unix" command it showed error as 
compilation terminated.
make[1]: **\* [util/env_win.o] Error 1 
make[1]: Leaving directory `/home/xen/namecoin/src/leveldb'
make: **\* [leveldb/libleveldb.a] Error 2.
What is that i should do to make it work ? Is there any other procedure for namecoin on daemon installation ?

**Comment by vijay-sutar** [comment]
I give you name coin deamon example.

git clone https://github.com/namecoin/namecoin.git
cd namecoin
qmake "USE_UPNP=-"
make
This produces the binary namecoin-qt in namecoin directory.

you can also build namecoind from the same repo (with the extra features, encrypt wallet and other rpc commands)

by

git clone https://github.com/namecoin/namecoin.git
cd namecoin/src
make

if .unix command not work then make command work
