### ISSUE TITLE
Bug? pool is empty

### ISSUE THREAD

**Issue by phelixbtc** [namecoin/namecoin-legacy#77]
> namecoind walletpassphrase "fancy pass phrase" 0
> 
> namecoind getinfo
> error: {"code":-1,"message":"ReserveKeyFromKeyPool() : pool is empty"}
> 
> namecoind walletpassphrase "fancy pass phrase" 9999
> 
> namecoind getinfo
> {
>     "version" : 37400,
>     ...
>     "errors" : ""
> }

edit: just realized I had actually generated a 100 keys in the meantime. Is it possible the keypool does not refill with a walletpassphrase timeout of "0"?

**Comment by domob1812** [comment]
Actually, my experience is that the keypool doesn't refill at all from "walletpassphrase" alone.  When I just unlock the wallet and lock it again, it is not filled.  Only when I call "getinfo" in between, the keypool is refilled.  So it seems that getinfo refills it, while walletpassphrase does not.

I don't know why this is the case and whether or not there is a good reason for this kind of behaviour or it is simply a "bug".  If we agree that walletpassphrase should instead refill the key pool, I can implement that.

**Comment by phelixbtc** [comment]
My impression was that "getinfo" would not refill with the timeout set to "0".

**Comment by domob1812** [comment]
No, it does not - since the wallet is locked again when you run "getinfo" after a "walletpassphrase" with timeout of 0.  But it would if you didn't use a timeout of 0.  What exactly are you trying to do with 0 timeout anyway?

**Comment by phelixbtc** [comment]
LOL. I wanted to unlock it indefinitely.
