### ISSUE TITLE
Changes to name filter

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-legacy#81]
Name filter is the only "bulk" retrieval method for records and it leaves much to be desired in terms of bulk exporting of information.  I'm requesting two minor changes or perhaps a `name_export` method call:
1.  `expires_in`  ->  `expire_block`: This is a very low-information field because it requires being in constant contact with the client, which isn't what you need if you are exporting documents in bulk.  It would appear to be trivial to fix this by simply grabbing the current block count and then subtracting from it but this leads to race conditions.
2. `name_show` mode: includes all of the information present in name_show.  This is mainly for backwards compatibility.

**Comment by domob1812** [comment]
Note that you can also use "name_scan" for bulk retrieval, which is what I use.  I think it is simpler, since you don't have to pass a "fake" regexp.  But that's probably a matter of taste.  Also, the information that name_scan returns is not the full name_show, either.

I think your requests are reasonable, this should be fixed (with low priority, although I may give it a try soon as it is probably very easy).

**Comment by indolering** [comment]
Does name_scan give you the ability to restrict results to current, registered domains?

**Comment by indolering** [comment]
Dates are really hard to pin down in general.  It's outside the scope of this ticket, but I posted some discussion on the forum to setting a more sensible renewal time period (closer to a year) and setting up a soft "expired" date for applications trying to figure out if it should resolve a given address.

Anyway, what about returning the best-guess expire date?  Right now, I'm basically dividing the expires_in value by 6 and adding that number of hours to a date object.  Not sure if its worth the effort of putting in here or not....  : /

**Comment by phelixbtc** [comment]
The date would always be wrong. IMHO it is a bad idea to display a date estimate, especially since it is so easy to calculate. What would be of interest is information on whether all blocks have been downloaded at all.

**Comment by phelixbtc** [comment]
I suggest for this discussion to be moved to the forum.
