### ISSUE TITLE
Determine Block Height from Block Hash

### ISSUE THREAD

**Issue by dlio** [namecoin/namecoin-legacy#87]
Is it possible to use namecoind to determine the block number from a block hash?
going the other way is easy:

```
namecoind getblockhash <index>
```

but getting the height from the hash appears to be impossible...

Height is not an attribute on each block and no method appears to return it.

The closest two are:

```
namecoind getblockcount
which:
"Returns the number of blocks in the longest block chain."
and
namecoind getblocknumber
which:
"Returns the block number of the latest block in the longest block chain."
```

So there are two methods which do the same thing and no methods that take a block hash and return that block's height, nor is block height a block attribute.

Is there something I'm missing here?  Other coins do not appear to lack this basic functionality.

**Comment by ryancdotorg** [comment]
This is not a feature that namecoin currently supports. I've written a patch to add that as well as a few other properties to the block data returned via RPC and will make a pull request after it's seen some testing and I've tried to add the rest of the missing data to it.

https://gist.github.com/ryancdotorg/5e610e9ee546beed367d

**Comment by phelixbtc** [comment]
Resolved as of https://github.com/namecoin/namecoin/pull/119
