### ISSUE TITLE
Post OS X builds

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin-legacy#90]
I believe that Cassini has working binaries of namecoind and Namecoin-QT that are compatible with the latest hard-fork.

I believe that all we need to do is have him sign off on the binaries/hash of the binaries using his PGP key.

After that, do we post a "new" release on Github or should I just move this ticket to namecoin.org?

**Comment by indolering** [comment]
Cassini has a 3.51 namecoind binary and is working on a Namecoin-QT one.  How should he distribute these?  Can someone do a PR for a binary release?

**Comment by phelixbtc** [comment]
I would prefer a release with GUI. You know these Mac people ;)

Closing as there is another issue open for this now: https://github.com/namecoin/namecoin/pull/108

**Comment by indolering** [comment]
I know mac developers too : p
