### ISSUE TITLE
Official Windows release at namecoin.info has no "listsinceblock" RPC function

### ISSUE THREAD

**Issue by piterop** [namecoin/namecoin-legacy#96]
I see "listsinceblock" RPC function binding in sources, but downloaded Windows release don't have this function, which is bad for developing tools cooperating with namecoin.

Other QT clients have this function in compiled Windows release, for example: ppcoin, primecoin, quarkcoin, dogecoin, darkcoin, litecoin

**Comment by phelixbtc** [comment]
You are absolutely right. The release candidate v0.3.75-rc1 has it: http://forum.namecoin.info/viewtopic.php?p=11499#p11499    It has many improvements but is not backward compatible with one particular database file so I recommend making and encrypted backup of your Namecoin data directory.   I have not noticed any problems with v0.3.75-rc1 so far and have not heard of any either. Probably we will soon make it the official version.
