### ISSUE TITLE
TLD for phone numbers

### ISSUE THREAD

**Issue by renne** [namecoin/namecoin-legacy#97]
Please add a TLD "e164" with 12-digit numeric subdomains to map phone numbers to IP-addresses. That way users can register numeric phone numbers in the namecoin namespace and map them to the IPs of their SIP phones. This would be an alternative for [Telephone number mapping](http://en.wikipedia.org/wiki/Telephone_number_mapping) which is suppressed by big Telcos. Phone numbers can have up to 15 digits which allows to request a 3-digit international dialing prefix from the ITU for PSTN-to-SIP-gateways.

**Comment by domob1812** [comment]
This sounds like an interesting usage (although I've never been into SIP so far myself).  However, I think you should start a discussion about it on the forum at https://forum.namecoin.info/ rather than here, since it relates more to the community than the actual code.
