### ISSUE TITLE
Namecoind web-GUI

### ISSUE THREAD

**Issue by renne** [namecoin/namecoin-legacy#99]
Hi,

Namecoind already provides a HTTP(S)-based RPC interface. To simplify maintanance and usage I suggest to add some HTML5/Javascript code for a web interface directly served by namecoind via HTTPS.

**Comment by phelixbtc** [comment]
You mean instead of the current GUI?

**Comment by renne** [comment]
For desktops I suggest to keep the QT interface to avoid security problems with browsers. But if namecoind runs as  a service on a headless server a web interface would be quite useful for administration. Using HTML5/Javascript with the RPC-API will allow to serve static HTML5/Javascript code via the already implemented HTTPS interface.

**Comment by phelixbtc** [comment]
Yeah, it sure would be nice. Note that https://github.com/namecoin/nmcontrol is prepared to offer a http gui.

**Comment by domob1812** [comment]
I believe that this would only bloat namecoind unnecessarily.  The RPC interface provides all necessary commands to do that (or it should be extended to do so).  However, I think that it is a great thing to have - to be implemented either in NMControl or in a separate package that builds on the RPC interface.

**Comment by renne** [comment]
I meant using the RPC interface:
Namecoind RPC <-- HTTP(S) --> Browser (HTML5/Javascript).

To avoid the installation of an extra webserver just to serve the static HTML5/Javascript files of the web-interface Namecoind should serve the static HTML5/Javascript files via the RPC interface. The HTML5/Javascript web-interface code itself can be developed in another project.

**Comment by phelixbtc** [comment]
Strategically any work on this should go into NMControl. Closing.
